name: CI for LunaTestTask with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.latest'

      # Build and run Docker Compose
      - name: Build Docker Compose containers
        run: docker-compose -f docker-compose.yml up -d --build

      # Run unit tests
      - name: Run unit tests
        run: docker exec -it lunatesttask dotnet test --no-restore --verbosity normal

      # Tear down the Docker containers after testing
      - name: Tear down Docker Compose
        run: docker-compose down
