name: CI for LunaTestTask

# Run this workflow every time there's a push to the main branch
on:
  push:
    branches:
      - main

# Specify the jobs for the workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Steps of the workflow
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Ensure it matches your .NET version

      # Install dependencies
      - name: Install dependencies
        run: dotnet restore LunaTestTask.sln

      # Build the project
      - name: Build
        run: dotnet build LunaTestTask.sln --configuration Release --no-restore

      # Run tests
      - name: Run unit tests
        run: dotnet test LunaTestTask.sln --no-restore --verbosity normal

